export { ReactComponent as Calendar } from "./calendar.svg";
export { ReactComponent as Clock } from "./clock.svg";
export { ReactComponent as Close } from "./close-lg.svg";
export { ReactComponent as Danger } from "./danger.svg";
export { ReactComponent as Edit } from "./edit.svg";
export { ReactComponent as Globe } from "./globe.svg";
export { ReactComponent as Trash } from "./trash.svg";
export { ReactComponent as Tweets } from "./tweets.svg";
export { ReactComponent as Twitter } from "./twitter.svg";
