const actions = {
  ADD_MESSAGE: "ADD_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  OPEN_MESSAGE_MODAL: "OPEN_MESSAGE_MODAL",
  CLOSE_MESSAGE_MODAL: "CLOSE_MESSAGE_MODAL",
  EDIT_MESSAGE: "EDIT_MESSAGE", //edit message action
};

export default actions;
